
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cr
 */
public class Principal extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Principal
     */
    
    Socket sc=null;
    ServerSocket server;
    Servidor s= new Servidor();
    
    public Principal() {
        initComponents();
        
        s.addObserver(this);
        Thread t = new Thread(s);
        t.start();
        
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("Menú Principal");

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        B_CerrarS = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        B_Alumnos = new javax.swing.JMenuItem();
        B_Educadoras = new javax.swing.JMenuItem();
        B_General = new javax.swing.JMenuItem();
        B_General1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        B_Registrar = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(122, 164, 255));

        jButton1.setText("Video de Apoyo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sesion.png"))); // NOI18N
        jMenu1.setText("Sesión");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sesion.png"))); // NOI18N
        jMenu5.setText("Opciones");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu5MouseExited(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sesion.png"))); // NOI18N
        jMenuItem1.setText("Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenu1.add(jMenu5);
        jMenu1.add(jSeparator1);

        B_CerrarS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_CerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sesion.png"))); // NOI18N
        B_CerrarS.setText("Cerrar Sesión");
        B_CerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_CerrarSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_CerrarSMouseExited(evt);
            }
        });
        B_CerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CerrarSActionPerformed(evt);
            }
        });
        jMenu1.add(B_CerrarS);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        jMenu2.setText("Inventario");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        B_Alumnos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        B_Alumnos.setText("Productos");
        B_Alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_AlumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_AlumnosMouseExited(evt);
            }
        });
        B_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AlumnosActionPerformed(evt);
            }
        });
        jMenu2.add(B_Alumnos);

        B_Educadoras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Educadoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        B_Educadoras.setText("Empleados");
        B_Educadoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_EducadorasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_EducadorasMouseExited(evt);
            }
        });
        B_Educadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EducadorasActionPerformed(evt);
            }
        });
        jMenu2.add(B_Educadoras);

        B_General.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_General.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        B_General.setText("Proveedores");
        B_General.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_GeneralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_GeneralMouseExited(evt);
            }
        });
        B_General.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GeneralActionPerformed(evt);
            }
        });
        jMenu2.add(B_General);

        B_General1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_General1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        B_General1.setText("Clientes");
        B_General1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_General1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_General1MouseExited(evt);
            }
        });
        B_General1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_General1ActionPerformed(evt);
            }
        });
        jMenu2.add(B_General1);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evaluaciones.png"))); // NOI18N
        jMenu4.setText("Ventas");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        B_Registrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evaluaciones.png"))); // NOI18N
        B_Registrar.setText("Registrar");
        B_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_RegistrarMouseExited(evt);
            }
        });
        B_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrarActionPerformed(evt);
            }
        });
        jMenu4.add(B_Registrar);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logos, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_EducadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EducadorasActionPerformed

        this.dispose();
        Empleados p = new Empleados();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);

    }//GEN-LAST:event_B_EducadorasActionPerformed

    private void B_CerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CerrarSActionPerformed

        this.dispose();
        InicioSesion p = new InicioSesion();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);

    }//GEN-LAST:event_B_CerrarSActionPerformed

    private void B_CerrarSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CerrarSMouseEntered
        // Dentro del boton

        logos.setSize(new Dimension(150, 250));
        logos.setPreferredSize(new Dimension(150, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/Salir.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_CerrarSMouseEntered

    private void B_CerrarSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CerrarSMouseExited
        // Fuera del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_CerrarSMouseExited

    private void B_EducadorasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EducadorasMouseEntered
        //Dentro del boton

        logos.setSize(new Dimension(250, 200));
        logos.setPreferredSize(new Dimension(250, 200));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_EducadorasMouseEntered

    private void B_EducadorasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EducadorasMouseExited
        // Fuera del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_EducadorasMouseExited

    private void B_AlumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AlumnosMouseEntered
        //Dentro del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_AlumnosMouseEntered

    private void B_AlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AlumnosMouseExited
        // Fuera del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_AlumnosMouseExited

    private void B_GeneralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_GeneralMouseEntered
        //Dentro del boton

        logos.setSize(new Dimension(200, 200));
        logos.setPreferredSize(new Dimension(200, 200));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_GeneralMouseEntered

    private void B_GeneralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_GeneralMouseExited
        // Fuera del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_GeneralMouseExited

    private void B_RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RegistrarMouseEntered
        //Dentro del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/RegistrarEvaluaciones.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_RegistrarMouseEntered

    private void B_RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RegistrarMouseExited
        // Fuera del boton

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/JosefaLogo.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_B_RegistrarMouseExited

    private void B_AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AlumnosActionPerformed

        this.dispose();
        Productos p = new Productos();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);

    }//GEN-LAST:event_B_AlumnosActionPerformed

    private void B_GeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GeneralActionPerformed

        this.dispose();
        Proveedores p = new Proveedores();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);

    }//GEN-LAST:event_B_GeneralActionPerformed

    private void B_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrarActionPerformed

        this.dispose();
        Ventas p = new Ventas();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);

    }//GEN-LAST:event_B_RegistrarActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseExited
        // TODO add your handling code here:

        logos.setSize(new Dimension(200, 250));
        logos.setPreferredSize(new Dimension(200, 250));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/JosefaLogo.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_jMenu5MouseExited

    private void jMenu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseEntered
        // TODO add your handling code here:
        logos.setSize(new Dimension(200, 200));
        logos.setPreferredSize(new Dimension(200, 200));
        logos.setHorizontalAlignment(logos.CENTER);
        ImageIcon obj = new ImageIcon(getClass().getResource("/Imagenes/Opciones.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logos.getWidth(), logos.getHeight(), Image.SCALE_DEFAULT));
        logos.setIcon(icono);
    }//GEN-LAST:event_jMenu5MouseEntered

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        /*this.dispose();
        Opciones p = new Opciones();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);*/
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Video2 V2 = new Video2(this, false);
         V2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_General1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_General1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_General1MouseEntered

    private void B_General1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_General1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_General1MouseExited

    private void B_General1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_General1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Clientes p = new Clientes();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);
    }//GEN-LAST:event_B_General1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem B_Alumnos;
    private javax.swing.JMenuItem B_CerrarS;
    private javax.swing.JMenuItem B_Educadoras;
    private javax.swing.JMenuItem B_General;
    private javax.swing.JMenuItem B_General1;
    private javax.swing.JMenuItem B_Registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel logos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
